# main text of home
name: Ergun Simsekoglu 
bio:  After completing high school with the Certificate of Honor, I was fortunate enough to be awarded a scholarship to study my B.Sc. Degree at Texas A&M University and later on, continuing to study at Rice University in Computer Science with a focus on artificial intelligence.<br/> I studied Computer Science to learn programming languages to become a codemaster and have a better understanding web and mobile development. I'm the first qualified international student to get a T-STEM scholarship, and I also had the honor of being accepted into the NASA Aerospace scholars program. With that hard work, and hard study, I had the privilege of an internship with companies such as Twitter and Spotify.<br/> Besides publishing on my Medium page, I also write articles for F1 Racing Türkiye, the world’s best-selling Formula 1 magazine.






# twitter summary info
description: A blog about stuff

# if it's an external image, update below for true
# better with square images
external-image: true
picture: assets/images/ergun.jpg

url: http://iszfan.github.io
# your url: https://ergunsimsekoglu.github.io/ergun/

permalink: /:title/

markdown: kramdown
highlighter: rouge

# To enable google analytics, supply your token below
# analytics-google: 'UA-MYANALYTICS'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, set to false
disqus: mydisqus

# if you don't have any of social below, comment the line
twitter: ergunsimsekoglu
# google: mygoogle
instagram: ergunsimsekoglu
# pinterest: mypinterest
linkedin: ergunsimsekoglu
# youtube: myyoutube
# spotify: myspotify
github: ergunsimsekoglu
medium: ergunsimsekoglu
# vimeo: myvimeo
# email: emyemai@gmail.com

authors:
    johndoe:
        name: John Doe
        bio: A Man who travels the world eating noodles
        external-image: false
        picture: assets/images/profile.jpg
        twitter: johndoe
    jamesfoster:
        name: James Foster
        bio: A Man who develops software with coffee
        external-image: false
        picture: assets/images/james.jpg
        twitter: jamesfoster

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: false

# if you don't need "about" or "blog", comment them out below
about: false
blog: false

# do you want to show the "read time" of the posts?
read-time: false

# do you want to show the "tags" inside the posts?
show-tags: false

# related posts inside a post?
related: false

# show next & prev links in blog post?
blog-nav-links: false

# show author block at the end of a post ?
show-author: false

# do you want some animations?
animation: false

sass:
    sass_dir: _sass
    style: :compressed

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, indigo-gh-pages.zip, Rakefile, screen-shot.png, travis.sh, tasks]
